spring:
  application:
    name: Acadelica
  datasource:
    url: jdbc:mysql://b4uoq0rshdc6ogtoeymt-mysql.services.clever-cloud.com:3306/b4uoq0rshdc6ogtoeymt
    username: uuhwblprjqiupwbx
    password: h0qjyL8ufIoKlvwMJWLJ
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true
      ddl-auto: update
  web:
    cors:
      allowed-origins: "http://localhost:5678"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"




    #url: jdbc:mysql://localhost:3306/acadelica_db
    #username: root
    #password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver